ANTHROPIC_VERSION = "2023-06-01";
DEFAULT_MODEL = "claude-sonnet-4-5"
DEFAULT_BASE_URL = "https://api.anthropic.com/v1/"
MAX_TOKENS = 8192
PLUGIN_NAME = "Claudette"
SETTINGS_FILE = "Claudette.sublime-settings"
DEFAULT_VERIFY_SSL = True
SPINNER_CHARS = ['·', '✢', '✳', '∗', '✻', '✽']
SPINNER_INTERVAL_MS = 250
